# Generated by Django 4.2.5 on 2024-01-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evacore', '0003_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jefe_directo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subalternos', to='evacore.profile'),
        ),
    ]
